[package]
name = "ioreg-proc"
version = "0.1.0"
authors = ["Matt Coffin <mcoffin@qw-corp.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]

[dependencies.syn]
version = "0.15"
features = [ "full" ]
